FROM python:3.8

ARG TAG=local

WORKDIR /usr/src/


# VARIABLES PREDEFINIDAS
ENV TEMPLATE_PYTHON_VERSION=${TAG}

ENV TEMPLATE_PYTHON_PYTHON_HOST=0.0.0.0
ENV TEMPLATE_PYTHON_PYTHON_PORT=5000
ENV TEMPLATE_PYTHON_PYTHON_GUNICORN_WORKERS=1
ENV TEMPLATE_PYTHON_PYTHON_GUNICORN_CONNECTIONS=1000
ENV TEMPLATE_PYTHON_PYTHON_NOMBRE_APP=app
ENV TEMPLATE_PYTHON_PYTHON_NOMBRE_FUNCION_APP=app


# EJECUCION
CMD gunicorn \
    -b ${TEMPLATE_PYTHON_PYTHON_HOST}:${TEMPLATE_PYTHON_PYTHON_PORT} \
    --reload \
    --workers=${TEMPLATE_PYTHON_PYTHON_GUNICORN_WORKERS} \
    --worker-connections=${TEMPLATE_PYTHON_PYTHON_GUNICORN_CONNECTIONS} \
    ${TEMPLATE_PYTHON_PYTHON_NOMBRE_APP}:${TEMPLATE_PYTHON_PYTHON_NOMBRE_FUNCION_APP}

EXPOSE ${TEMPLATE_PYTHON_PYTHON_PORT}


# DEPENDENCIAS
RUN pip install compile --upgrade pip

COPY ./requirements.txt .
COPY ./files ./files

RUN pip install -r requirements.txt
RUN rm requirements.txt


# COMPILACION
COPY ./apps ./src/apps
COPY ./app.py ./src

RUN python -m compile -b -f -o ./dist ./src
RUN mv -f ./dist/src/* .